server:
  port: 8080

eureka:
  instance:
    hostname: localhost
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000

zuul:
  ignored-services: '*'
  prefix: /api
  routes:
    register-service:
      path: /event-register/**
      serviceId: event-register-api
  host:
    socket-timeout-millis: 30000


---

spring:
  profiles: docker

eureka:
  instance:
    hostname: shop-gateway-server
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://shop-eureka-server:9091/eureka/
  server:
    wait-time-in-ms-when-sync-empty: 3000